version: '3'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  loadtester:
    build:
      context: .
      dockerfile: Dockerfile.loadtest
    depends_on:
      - flaskapp

  gqltest:
    build:
      context: .
      dockerfile: Dockerfile.loadtest
    depends_on:
      - flaskapp
    volumes:
      - .:/load_test
    command: bash -c 'python gql_test.py'
