version: '3'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  loadtester:
    build:
      context: .
      dockerfile: Dockerfile.loadtest
    depends_on:
      - flaskapp
