# Use an official Python runtime as the parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /load_test

# Copy only the load test script and requirements into the container
COPY load_test.py requirements.txt /load_test/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "load_test.py"]
